
language: generic

matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    compiler: gcc
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
          - g++-8
  - os: osx
    sudo: required
    osx_image: xcode11
    compiler: clang

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -fs /usr/bin/gcc-8 /usr/local/bin/gcc; sudo ln -fs /usr/bin/g++-8 /usr/local/bin/g++; fi

script:
  - make clean all check _CXXFLAGS="-Werror"
  - ./bench
